name: Build and Deploy

on:
  push:
    branches: source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12.x'

    - name: Install deps
      run: npm install --production

    - name: Build and deploy
      run: npm run deploy

